# Generated by Django 5.2 on 2025-05-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_created_at_service_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.CharField(default='/default.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
